// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParserDAL.DataAccess;

#nullable disable

namespace ParserDAL.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    [Migration("20221007223629_Switched tables names to lowercase 2")]
    partial class Switchedtablesnamestolowercase2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParserDAL.Models.HeadmanAnnotation", b =>
                {
                    b.Property<string>("stream_group")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("day")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("parity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("annotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("stream_group", "day", "parity");

                    b.ToTable("headman_annotations");
                });

            modelBuilder.Entity("ParserDAL.Models.HeadmanChange", b =>
                {
                    b.Property<string>("stream_group")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("day")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("parity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pair_number")
                        .HasColumnType("integer");

                    b.HasKey("stream_group", "day", "parity");

                    b.ToTable("headman_changes");
                });

            modelBuilder.Entity("ParserDAL.Models.HeadmanSchedule", b =>
                {
                    b.Property<string>("stream_group")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("day")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("parity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("stream_group", "day", "parity");

                    b.ToTable("headman_schedules");
                });

            modelBuilder.Entity("ParserDAL.Models.PersonalAnnotation", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("stream_group")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("day")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("parity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("annotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id", "stream_group", "day", "parity");

                    b.ToTable("personal_annotations");
                });

            modelBuilder.Entity("ParserDAL.Models.PersonalChange", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("stream_group")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("day")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("parity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pair_number")
                        .HasColumnType("integer");

                    b.HasKey("id", "stream_group", "day", "parity");

                    b.ToTable("personal_changes");
                });

            modelBuilder.Entity("ParserDAL.Models.PersonalSchedule", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("stream_group")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("day")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("parity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id", "stream_group", "day", "parity");

                    b.ToTable("personal_schedules");
                });

            modelBuilder.Entity("ParserDAL.Models.SharedSchedule", b =>
                {
                    b.Property<string>("stream_group")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("day")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("parity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("stream_group", "day", "parity");

                    b.ToTable("shared_schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
