// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParserDAL.DataAccess;

#nullable disable

namespace ParserDAL.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    [Migration("20220812122538_SwitchedToLowerCase")]
    partial class SwitchedToLowerCase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParserDAL.Models.HeadmanAnnotation", b =>
                {
                    b.Property<string>("annotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stream_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("HeadmanAnnotations");
                });

            modelBuilder.Entity("ParserDAL.Models.HeadmanChange", b =>
                {
                    b.Property<string>("changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pair_number")
                        .HasColumnType("integer");

                    b.Property<string>("parity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stream_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("HeadmanChanges");
                });

            modelBuilder.Entity("ParserDAL.Models.HeadmanSchedule", b =>
                {
                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stream_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("HeadmanSchedules");
                });

            modelBuilder.Entity("ParserDAL.Models.PersonalAnnotation", b =>
                {
                    b.Property<string>("annotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("parity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stream_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("PersonalAnnotations");
                });

            modelBuilder.Entity("ParserDAL.Models.PersonalChange", b =>
                {
                    b.Property<string>("changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<int>("pair_number")
                        .HasColumnType("integer");

                    b.Property<string>("parity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stream_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("PersonalChanges");
                });

            modelBuilder.Entity("ParserDAL.Models.PersonalSchedule", b =>
                {
                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("parity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stream_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("PersonalSchedules");
                });

            modelBuilder.Entity("ParserDAL.Models.SharedSchedule", b =>
                {
                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stream_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("SharedSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
